
ccflags-y += -I$(srctree)/drivers/misc/mediatek/mtprof/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hibcore
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/base/power/$(MTK_PLATFORM)/
TMP_CFLAGS := -I$(src)/../common
ccflags-y  += $(TMP_CFLAGS)

obj-y += ak4376.o

