ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/shine_lite_GT9XX/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/shine_lite_GT9XX/include/$(CONFIG_GT9XXTB_FIRMWARE)/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/shine_lite_GT9XX/include/$(CONFIG_GT9XXTB_CONFIG)/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/

obj-y	+=  gt9xx_driver.o
obj-y	+=  goodix_tool.o
obj-y	+=  gt9xx_update.o

