#Added start by wenshengfan,2015/12/7
#include $(srctree)/drivers/misc/mediatek/Makefile.custom
ccflags-y += -I$(srctree)/drivers/misc/mediatek/alsps/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include

obj-y	:=  rohm_rpr0521_i2c.o
#Added end by wenshengfan,2015/12/7
