#include $(srctree)/drivers/misc/mediatek/Makefile.custom

#begin: modify by binpeng.huang.hz@tcl.com on 2016.08.16
obj-$(CONFIG_NFC_MT6605)  += mt6605.o
obj-$(CONFIG_NFC_PN54X)   += pn54x.o
ccflags-y +=  -DDEBUG
#end: modify by binpeng.huang.hz@tcl.com on 2016.08.16
